/*
 * Copyright (c) 2020-2023 Datamixin.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  tutorialSidebar: [
    {
      id: "index",
      type: "doc",
    },
    {
      label: "Get Started",
      type: "category",
      items: [
        {
          id: "get-started/docker",
          type: "doc",
        },
        "get-started/short-guide",
      ],
    },
    {
      label: "Dataset",
      type: "category",
      items: [
        {
          id: "dataset/overview",
          type: "doc",
        },
      ],
    },
    {
      label: "Data Preparation",
      type: "category",
      items: [
        {
          id: "data-preparation/overview",
          type: "doc",
        },
        {
          id: "data-preparation/handling-missing-data",
          type: "doc",
        },
      ],
    },
    {
      label: "Data Visualization",
      type: "category",
      items: ["data-visualization/overview"],
    },
    {
      label: "Machine Learning",
      type: "category",
      items: ["machine-learning/overview"],
    },
  ],
};

module.exports = sidebars;
